spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Frochy/SpringCloudConfig
          search-paths: respo
          username: Frochy
          password: Xyj19980607
      label: master
server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
